goToTop = true
sitename = "infosec MNIT"
defaultColor = "auto"
description = "Infosec Club of MNIT Jaipur"
toc = true
rssFeedDescription = "full"

[author]
	avatar = "mnit_logo.png"
	intro = "Infosec MNIT"
	name = "Sidharth R"
	description = "Official Infosec club of MNIT Jaipur"

# Social icons that are shown on the homepage
[[socialIcons]]
name = "github"
url = "https://github.com/infosec-MNIT"

[[socialIcons]]
name = "Rss"
url = "index.xml"

[[socialIcons]]
name = "ctftime"
url = "placeholder"
